version: '3'
services:
  web:
    image: nginx:alpine
    platform: linux/x86_64
    volumes:
      - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./web:/var/www/html/public"
    ports:
      - "8000:80"
    restart: always